config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 resources :users, :only => [:show]
 resources :users do
  		member do
    		get 'be_premium'
        get 'apply_premium'
        get 'enable_premium'
        get 'disable_premium'
        get 'mascreditos'
        get 'menoscreditos'
 		end
	end
 match '/users',   to: 'users#index',   via: 'get'
  resources :auctions do
      member do
        get 'finalizar'
   end
  end     

  resources :hotsales
  resources :residences
  resources :home
  resources :reservations
  #devise_for :users, controllers: {
  #      sessions: 'users/sessions'
  #    }
  get 'auctions/:id', to:'auctions#puja'
  post '/auctions/:id', to: 'auctions#puja'
  post '/residences/:id', to: 'residences#show'
  root :to => "home#index"
end

app/models/auction.rb
class Auction < ApplicationRecord
	validate :validate_week

  private

  def validate_week
  	  date = DateTime.parse(weekdate)
      if date.present? && date < Date.today + 6.month
          errors.add(:weekdate, 'Debes reservar con 6 meses de anticipacion')
      end
  end	
  belongs_to :user
	belongs_to :residence
	has_many :bids
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

def index
		@auction = Auction.all
		@tasks = if !params[:weekini].blank? and !params[:weekfin].blank?
          
        @NoPueden = Auction
        .where('weekdate BETWEEN ? AND ?', "#{params[:weekini]}", "#{params[:weekfin]}")
        #.pluck(:residence_id)
     	#@Sipueden = Residence.all.where.('id NOT IN (?)', Array.wrap(@NoPueden))
    	@Sipueden = Auction.where(id: @NoPueden)
     	@auction = @Sipueden 
     	end
    	
	end



	def create
		@auction = Auction.new(auction_params)
		@auction.user_id = 1
		if  ( Reservation.where(residence_id: @auction.residence_id, weekdate: @auction.weekdate).exists? or Hotsale.where(residence_id: @auction.residence_id, weekdate: @auction.weekdate).exists? or Auction.where(residence_id: @auction.residence_id, weekdate: @auction.weekdate).exists?)
			redirect_to auctions_path, notice: 'No puede crear subasta en esa fecha, ya esta reservada o en hotsale o en subasta'
		else 
			if @auction.save
			redirect_to auctions_path, notice: 'La subasta creada'
			else
				redirect_to auctions_path, notice: 'La subasta no tiene 6 meses de anticipacion'
			end
		end
	end

	
	def show
		@auction = Auction.find(params[:id])
	end


	def destroy
		@auction = Auction.find(params[:id])	
		if current_user.admin?
		  if @auction.user.id != 1
		    if @auction.user.creditos > 0
			  		@reservation = Reservation.new(residence: @auction.residence, user: @auction.user,  weekdate: @auction.weekdate, modo: "subasta")
					if @reservation.save
					   @auction.user.update(creditos: @auction.user.creditos - 1)
					   @auction.destroy
					   redirect_to auctions_path, notice: "Subasta vendida exitosamente"
					end
			  else
			    @auction.update( user_id: 1 ) 
			    redirect_to auctions_path, notice: "Error en la venta de subasta, pulse nuevamente para eliminar o espere a que otro usuario puje" 
			  end
		   else @auction.destroy
				redirect_to auctions_path, notice: "Nadie pujo, subasta eliminada" 
			 end
		end
	end


	def edit
		@auction = Auction.find(params[:id])
	end


	def update
		@auction = Auction.find(params[:id])
		
			if @auction.update( auction_params)
				redirect_to auctions_path, notice: 'La subasta modificada'
			else
				redirect_to auctions_path, notice: 'La subasta no tiene 6 meses de anticipacion'
			end
		
	end


	def auction_params
		params.require(:auction).permit(:name, :user_id, :weekdate, :residence_id, :monto, :minimapuja)
	end

	def new
		@auction = Auction.new
	end

	def finalizar
	    @auction = Auction.find(params[:id])
	    @auction.name = "finalizada"
	    @auction.save
	    redirect_to auctions_path, notice: 'Su solicitud ha sido enviada con exito.'
  end


end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/edit.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">




<h1>  Editar subasta </h1>

<% if current_user.try(:admin?) %>
	<%= form_for @auction do |f| %>
		
	
  		<div>
			
				<%= f.label :monto, 'MONTO' %>
  				<%= f.number_field :monto, class: 'form-control', required: true %>
  		
  		</div>
<p></p>
  		<div>
			
				<%= f.label :minimapuja, 'PUJA MINIMA' %>
  				<%= f.number_field :minimapuja, class: 'form-control',required: true %>
  			
  		</div>
<p></p>

  		<%= f.submit "Editar subasta", class: 'btn btn-primary' %>
      <%= link_to "Volver", auctions_path, class: 'btn btn-primary' %>
  	</div>
<% end %>
<% end %>
  <div class="col-md-3"></div> 

</div>
</div>

app/views/auctions/index.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">

<p></p>
<table class="table">
	<thead>
<%= form_tag(auctions_path, method: :get) do %>
<div class="form-group">
 Disponibilidad desde semana inicial:
	<%= week_field_tag :weekini, params[:weekini] %>
</div>
<div class="form-group">
 Disponibilidad desde semana final:
  <%= week_field_tag :weekfin, params[:weekfin] %>
</div>
<%= submit_tag 'Buscar' %>
<% end %>

<table class="table">
	<thead>
		<tr>
			<th>Residencia</th>
			<th>Semana del:</th>
			
			<th>Base</th>
			<th>Estado</th>
			<% if current_user.try(:admin?) %>
			<th>Puja Minima</th>
			<th></th>
			<% end %>
		</tr>
	</thead>
<tbody>
		<% @auction.each do |r| %>
			<tr> <% @r = Residence.find(r.residence_id) %>
       		 <td> <%=  @r.name  %></td>
		     <% date = DateTime.parse(r.weekdate)%>
         	 <td><%= date.strftime('%d/%m/%Y')   %></td>					
			 <td><%= r.monto %></td>
			 <td><%=r.name  %></td>
			
			<% if current_user.try(:admin?) %>
				<td><%= r.minimapuja %></td>
			<% end %>
				
			<% if r.name == "iniciada" %>
				<td><%=link_to 'ver', r, class: 'btn btn-success'%></td>
			<% end %>
				
			<% if current_user.try(:admin?) %>
				
				<td><%=link_to 'editar', edit_auction_path(r), class: 'btn btn-info'%></td>
				<td><%=link_to 'Finalizar', r, method: :delete,  class: 'btn btn-danger', data: { confirm: 'Realmente desea finalizar subasta?'} %>
			<% end %>

			</td>
				<% end %>
			</tr> 		
	</tbody>
</table>

  <div class="col-md-3"></div> 

</div>
</div>

app/views/auctions/new.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">



<h1>  Crea una nueva subasta </h1>
<% if current_user.try(:admin?) %>



	<%= form_for @auction do |f| %>
      <div class="form-group">
        <%= f.label :name, 'NOMBRE' %>
        <%= f.collection_select :name, Residence.all, :name , :name ,{}, class: 'form-control'%>
      <p></p>
		  <div>
			  <%= f.label :des, 'DESCRIPCION' %>
  		  <%= f.text_field :des, class: 'form-control' , required: true %>
  		</div>
  		<p></p>
  		<div>
				<%= f.label :monto, 'MONTO' %>
  			<%= f.number_field :monto, class: 'form-control', required: true %>
  			</div>
  		</div>
      <p></p>
  		<div>
				<%= f.label :minimapuja, 'PUJA MINIMA' %>
  			<%= f.number_field :minimapuja, class: 'form-control', required: true %>
  		</div>

      <p></p>

  		<%= f.submit "Crear subasta", class: 'btn btn-primary' %>
      <%= link_to "Volver", auctions_path, class: 'btn btn-primary' %>

  	</div>
<% end %>
<% end %>
  <div class="col-md-3"></div> 

</div>
</div>

app/views/auctions/show.html.erb
<div class="container">
  <div class="row">

<div class="col-md-3"></div>
  <div class="col-md-5">
<% if @auction.name == "iniciada"  %>
    <% if user_signed_in? %>

        <%if current_user.creditos > 0 %>
            <% @r = Residence.find(@auction.residence_id) %>
            <td>Residencia: <%=  @r.name  %></td>
            <h6>Puja Maxima Actual: <%= @auction.monto %></h6>
            <h6>Minima Puja: <%= @auction.minimapuja %></h6>
        
        <%= form_for @auction do |f| %>
             <strong><h4> <%= f.label :monto, 'Monto a pujar:' %></h4></strong>
             <%= f.number_field :monto,min: @auction.minimapuja+@auction.monto , class: 'form-control' %>
             <%= f.hidden_field :user_id, value: current_user.id %>
             <%= f.submit "PUJAR", class: 'btn btn-primary' %>
             <%= link_to "Volver", auctions_path, class: 'btn btn-primary' %>
        <% end %>
        <% else %>
          <h6>No dispone de creditos para poder pujar</h6>
        <% end %>
  <% end %>
<% end %>

</div>
</div>
</div>   

<div class="col-md-3"></div> 