config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 resources :users, :only => [:show]
 resources :users do
  		member do
    		get 'be_premium'
        get 'apply_premium'
        get 'enable_premium'
        get 'disable_premium'
        get 'mascreditos'
        get 'menoscreditos'
 		end
	end
 match '/users',   to: 'users#index',   via: 'get'
  resources :auctions do
      member do
        get 'finalizar'
   end
  end     

  resources :hotsales
  resources :residences
  resources :home
  resources :reservations
  #devise_for :users, controllers: {
  #      sessions: 'users/sessions'
  #    }
  get 'auctions/:id', to:'auctions#puja'
  post '/auctions/:id', to: 'auctions#puja'
  post '/residences/:id', to: 'residences#show'
  root :to => "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates_length_of :card, minimum: 16
  validates_length_of :cvv, minimum: 3
  validates :age, :presence => true
  validate :validate_age

  private

  def validate_age
      if age.present? && age > 18.years.ago.to_date
          errors.add(:age, 'Debes ser mayor de 18 años.')
      end
  end

  enum premium: { si: 0, solicitado: 1, no: 2 }

  scope :admins, -> {where(admin: 1)}
 
  has_many :reservations
  has_many :auctions
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	@user = User.find(params[:id])
  	end



 def indexAdmins
    @admin = User.admins
  end

  def new
  	@user = User.new
  end

  def newAdmin
    @admin = User.new
  end

  def create
    @user = User.new( user_params )
    if @user.save
        redirect_to users_path, notice: "Se añadio un usuario exitosamente."
    else
      render :new
    end
  end

  def createAdmin
    @admin = User.new( user_params)
    if @admin.save
      redirect_to admins_path, notice: "Se añadio un admin exitosamente."
    else
      @error = "Contrasena muy debil"
      render :newAdmin
    end
  end

  def show
  	@user = User.find(params[:id])
  end

  def destroy
    @user = User.destroy(params[:id])
    redirect_to users_path
  end

  def destroyAdmin
    @admin = User.destroy(params[:id])
    redirect_to admins_path
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end
  #Usado para mandar parametros del usuario. Lo uso en la modificacion del usuario para actualizar los datos.
  #Se puede usar para otros metdos, como por ej. create.
  def user_params
    params.require(:user).permit(:name, :email, :password, :creditos, :admin, :age, :card, :cvv, :exp)
  end

  def be_premium
    @user = User.find(params[:id])
  end

  def apply_premium
    @user = User.find(params[:id])
    @user.premium = "solicitado"
    @user.save
    redirect_to current_user, notice: 'Su solicitud ha sido enviada con exito.'
  end

  def enable_premium
    @user = User.find(params[:id])
    @user.premium = "si"
    @user.save
    redirect_to users_path
  end

  def disable_premium
    @user = User.find(params[:id])
    @user.premium = "no"
    @user.save
    redirect_to users_path
  end

   def mascreditos
    @user = User.find(params[:id])
    @user.creditos = @user.creditos + 1
    @user.save
    redirect_to users_path
  end

  def menoscreditos
    @user = User.find(params[:id])
    @user.creditos = @user.creditos + 1
    @user.save
    redirect_to users_path
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">

<div class="centered">
	<h1> Listado de Usuarios </h1>  
	<br>
	<table class="table">
			
			<th> Email </th>
	
			<th> Categoria Premium </th>
		</tr>

			<% users = User.all %>
			<% users.each do |user| %>
				
				<% if not user.admin%> 
					<tr>
											
						<td> <%= user.email %> </td>
						
						<%if user.premium == "si" %>
							<td>SI</td>
						<% else %>
							<%if user.premium == "solicitado" %>
								<td>SOLICITADO</td>
							<% else %>
								<td>NO</td>
							<% end %>
						<% end %>
						 
						<% if current_user.admin? %>
					      <% if user.premium == "solicitado" %> 
					        <td><%= link_to "Hacer Premium", enable_premium_user_path(user), class: 'btn btn-warning' %></td>
					      <% else %> 
					        <% if user.premium == "si" %> 
					          <td><%= link_to "Baja Premium", disable_premium_user_path(user), class: 'btn btn-info' %></td>
					          <td><%= link_to "Mas Creditos", mascreditos_user_path(user), class: 'btn btn-dark' %></td>
					      	<% else %>
					      	<td><%= link_to "Mas Creditos", mascreditos_user_path(user), class: 'btn btn-dark' %></td> 
					      		<td></td>
					      	<% end %>
					      <% end %>
					    <% end %>

			      		<td><%= link_to "Borrar", user, method: :delete,  class: 'btn btn-danger btn-sm', data: { confirm: 'Realmente desea borrar este usuario?'}%></td>
					</tr>
				<% end %>
			<% end %>

			<% if users.size == 0 %>
				<tr> <td colspan="3"> No hay usuarios </td> </tr>
			<% end %>

	</table>

		
		<p> <%= link_to "Volver a pagina de inicio", root_path, class: 'btn btn-secondary' %> </p><% if current_user.admin? %>
	<td><%= link_to "Mas Creditos ADMIN", mascreditos_user_path(current_user.id), class: 'btn btn-warning' %></td> 
		<% end %>

</div>

  <div class="col-md-3"></div> 

</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">
 
  <h1>Perfil</h1>
  
<div class="profile">
  <table class="profile-table">
    
    <tr>
      <td class="bold"> Email </td>
      <td class="profile-field"><%= @user.email %></td>
    </tr>
    <tr>
      <td class="bold"> Creado el </td>
      <td class="profile-field"><%= @user.created_at %></td>
    </tr>
    <p> Creditos: <%= @user.creditos %> </p>
    <p> Usuario Premium: <%= @user.premium %> </p>
    <p> Nacimiento: <%= @user.age %> </p>

    
    <tr><% if @user.admin? %>
      <td class="bold"> Administrador </td>
      <td class="profile-field"><%= @user.admin %></td>
    </tr>
  </table>
</div>
  <%else%>
    

    
    <% if !current_user.admin? %> 
      <% if current_user.premium == "no" %> 
          <tr><%= link_to "Pasar a ser premium", apply_premium_user_path, class: 'btn btn-info' %></tr>
      <% end %>
    <% else %> 
      <% if @user.premium == "solicitado" %> 
        <tr><%= link_to "Habilitar usuario a ser premium", enable_premium_user_path, class: 'btn btn-info' %></tr>
      <% else %>
        <% if @user.premium == "si" %> 
          <tr><%= link_to "Desabilitar usuario de condicion premium", disable_premium_user_path, class: 'btn btn-danger' %></tr>
        <% end %>
      <% end %>
    <% end %>
    
    
  <% end %>


  <table class="table">
  <thead>
    <tr>
      
      <th>RESIDENCIA</th>
      <th>Semana del:</th>
      <th>Modo </th>
       <th>      </th>   
    </tr>
  </thead>
  <tbody>
    <% @reservas = @user.reservations %>
    <% @reservas.each do |r| %>
      <tr>
              
        <% @r = Residence.find(r.residence_id) %>
        <td><%=  @r.name  %></td>

        <% date = DateTime.parse(r.weekdate)%>
         <td><%= date.strftime('%d/%m/%Y')   %></td>
        <td><%= r.modo  %></td>
        <td><%=link_to 'Cancelar reserva', r , method: :delete,  class: 'btn btn-danger', data: { confirm: 'Realmente desea eliminar reserva?'} %></td>
 
        <% end %>
      </tr> 
    

  </tbody>
</table>
  <td><%= link_to "Volver", root_path, class: 'btn btn-secondary' %></td>
  <td><%= link_to "Editar perfil", edit_user_registration_path(@user), class: 'btn btn-dark '%></td>

</div>
 <div class="col-md-3"></div> 

</div>
</div>