config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 resources :users, :only => [:show]
 resources :users do
  		member do
    		get 'be_premium'
        get 'apply_premium'
        get 'enable_premium'
        get 'disable_premium'
        get 'mascreditos'
        get 'menoscreditos'
 		end
	end
 match '/users',   to: 'users#index',   via: 'get'
  resources :auctions do
      member do
        get 'finalizar'
   end
  end     

  resources :hotsales
  resources :residences
  resources :home
  resources :reservations
  #devise_for :users, controllers: {
  #      sessions: 'users/sessions'
  #    }
  get 'auctions/:id', to:'auctions#puja'
  post '/auctions/:id', to: 'auctions#puja'
  post '/residences/:id', to: 'residences#show'
  root :to => "home#index"
end

app/models/residence.rb
class Residence < ApplicationRecord
	#validates :name, presence: true
	#validates :des, presence: true
	has_many :reservations , :dependent => :delete_all
	has_many :auctions, :dependent => :delete_all
	has_many :hotsales, :dependent => :delete_all

end

app/controllers/residences_controller.rb
class ResidencesController < ApplicationController
	
	def residence_params
	  params.require(:residence).permit(:name, :term)
	end

	def index
  @residences = Residence.all
    @tasks = if !params[:weekini].blank? and !params[:weekfin].blank?
          
          @NoPueden = Reservation
            .where('weekdate BETWEEN ? AND ?', "#{params[:weekini]}", "#{params[:weekfin]}")
            .pluck(:residence_id)
    #@Sipueden = Residence.all.where.('id NOT IN (?)', Array.wrap(@NoPueden))
    @Sipueden = Residence.where.not(id: @NoPueden)
    @residences = @Sipueden 
    #else 
    # flash[:notice] = 'Inicial menor de 6 meses' end
    end
    if !params[:term].blank?
     if @Sipueden != nil
      @residences = @Sipueden.where('name ILIKE ? OR pais ILIKE ? OR localidad ILIKE ? OR provincia ILIKE ? OR des ILIKE ? ', "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%")
      else 
        @residences = Residence.all.where('name ILIKE ? OR pais ILIKE ? OR localidad ILIKE ? OR provincia ILIKE ? OR des ILIKE ? ', "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%")
      end
     end    
 end

	def create
		@residence = Residence.new(params.require(:residence).permit(:name, :des, :location, :pais, :provincia, :localidad))
		if @residence.save
			redirect_to residences_path, notice: 'Se creo la residencia'
		else
			render :new
		end
	end

	def show
		@residence = Residence.find(params[:id])
	end

	def destroy
		residence = Residence.find(params[:id])
		if residence.destroy
			redirect_to residences_path, notice: "La residencia fue borrada"
		else
			redirect_to residences_path, notice: "La residencia no fue borrada"	
		end
	end


	def edit
		@residence = Residence.find(params[:id])
	end


	def update
		@residence = Residence.find(params[:id])
		if @residence.update(params.require(:residence).permit(:name, :des, :location, :pais, :provincia, :localidad))
			redirect_to residences_path, notice: 'La residencia se modifico correctamente'
		end
	end


	def new
		@residence = Residence.new
	end
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/residences/edit.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">


<h1>  Crea una nueva residencia </h1>


	<%= form_for @residence do |f| %>
		
	   <div>
      <div>
        <%= f.label :name, 'NOMBRE' %>
          <%= f.text_field :name, class: 'form-control',required: true %>
        </div>
      </div>

      <p></p>
    <div>
      <div>
        <%= f.label :des, 'DESCRIPCION' %>
          <%= f.text_field :des, class: 'form-control',required: true %>
        </div>
      </div>
<p></p>
<div>
      <div>
        <%= f.label :pais, 'PAIS' %>
          <%= f.text_field :pais, class: 'form-control',required: true %>
        </div>
      </div>
<p></p>
      <div><div>
      <div>
        <%= f.label :provincia, 'PROVINCIA' %>
          <%= f.text_field :provincia, class: 'form-control',required: true %>
        </div>
      </div>
<p></p>
<div>
      <div>
        <%= f.label :localidad, 'LOCALIDAD' %>
          <%= f.text_field :localidad, class: 'form-control',required: true %>
        </div>
      </div>
<p></p>
      <div>
        <%= f.label :location, 'URL IMAGEN' %>
          <%= f.text_field :location, class: 'form-control', required: true %>
        </div>

  		<p></p>
  		<%= f.submit "Editar residencia", class: 'btn btn-primary' %>
      <%= link_to "Volver", residences_path, class: 'btn btn-primary' %>
  	
<% end %>

  <div class="col-md-3"></div> 

</div>
</div>

app/views/residences/index.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">

<div id="demo" class="carousel slide" data-ride="carousel">

 
  
  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="http://lgtv.cl.s3.amazonaws.com/wp-content/uploads/2015/05/16123335/LG-grupos-socioeconomicos-800x400.jpg" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="https://hips.hearstapps.com/es.h-cdn.co/fotoes/images/noticias/videojuegos/minecraft-bate-records-en-xbox-live-arcade/5550658-1-esl-ES/Minecraft-bate-records-en-Xbox-Live-Arcade.jpg?crop=1xw:0.8888888888888888xh;center,top&resize=1200:*" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="http://www.toursbariloche.com/wp-content/uploads/2016/05/BLEST1-800x400.jpg" width="1100" height="500">
    </div>
  </div>
  
  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
<p></p>

<%= form_tag(residences_path, method: :get) do %>
<p> Buscar: 
  <%= text_field_tag :term, params[:term] %></p>

<p> Disponibilidad desde semana inicial:
  <%= week_field_tag :weekini, params[:weekini] %></p>

<p> Disponibilidad desde semana final:
  <%= week_field_tag :weekfin, params[:weekfin] %></p>

<%= submit_tag 'Buscar' %>

<% end %>
</p>

<table class="table">
  <thead>
    <tr>
      <th>NOMBRE</th>
      <th>DESCRIPCION</th>
      <th>PAIS</th>
      <th>PROVINCIA</th>
      <th>LOCALIDAD </th>
      
    </tr>
  </thead>
  <tbody>
    <% for residence in @residences %>
      <tr>
        <td><%= residence.name %></td>
        <td><%= residence.des %></td>
        <td><%= residence.pais %></td>
        <td><%= residence.provincia %></td>
        <td><%= residence.localidad %></td>
       
        <td></td>
        <td>
          <%=link_to 'ver', residence, method: :show, class: 'btn btn-success'%>
          <% if current_user.try(:admin?) %>
          <%=link_to 'editar', edit_residence_path(residence), class: 'btn btn-info'%>
          <%=link_to 'eliminar', residence, method: :delete,  class: 'btn btn-danger', data: { confirm: 'Realmente desea eliminar residencia?'} %>
          <% end %>
        </td>
      </tr> 
    <% end %>
  </tbody>
</table>
<p></p>
<div class="row">
<% if current_user.try(:admin?) %>
<%= link_to 'Nueva residencia', new_residence_path, class: 'btn btn-primary' %>
<% end %>
</div>

<div class="col-md-3"></div> 

</div>
</div>

app/views/residences/new.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">

<h1>  Crea una nueva residencia </h1>


<% if current_user.try(:admin?) %>
	<%= form_for @residence do |f| %>
		
		<div>
			<div>
				<%= f.label :name, 'NOMBRE' %>
  				<%= f.text_field :name, class: 'form-control',required: true %>
  			</div>
  		</div>

      <p></p>
		<div>
			<div>
				<%= f.label :des, 'DESCRIPCION' %>
  				<%= f.text_field :des, class: 'form-control',required: true %>
  			</div>
  		</div>
<p></p>
<div>
      <div>
        <%= f.label :pais, 'PAIS' %>
          <%= f.text_field :pais, class: 'form-control',required: true %>
        </div>
      </div>
<p></p>
  		<div><div>
      <div>
        <%= f.label :provincia, 'PROVINCIA' %>
          <%= f.text_field :provincia, class: 'form-control',required: true %>
        </div>
      </div>
<p></p>
<div>
      <div>
        <%= f.label :localidad, 'LOCALIDAD' %>
          <%= f.text_field :localidad, class: 'form-control',required: true %>
        </div>
      </div>
<p></p>
			<div>
				<%= f.label :location, 'URL IMAGEN' %>
  				<%= f.text_field :location, class: 'form-control', required: true %>
  			</div>
  		</div>
      <p></p>
  		<%= f.submit "Crear residencia", class: 'btn btn-primary' %>
  	</div>
<% end %>
<% end %>
  <div class="col-md-3"></div> 

</div>

app/views/residences/show.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">


<img src="<%= @residence.location %>" style="max-width:100%;width:auto;height:auto;">

<h1><%= @residence.name %></h1>
<p><%= @residence.des %></p>

<%if Auction.exists?(residence_id: params[:id]) %>
	<%= link_to "FECHAS EN SUBASTA DISPONIBLES", auctions_path , :class=>'btn btn-success' %>
<% else %>

<div class="col-md-3"></div>


<% if current_user.premium == "si" %> 
	<strong><h5>Reserva directa: </h5></strong>
  <%if current_user.creditos > 0 %>
	<%= form_for Reservation.new() do |f| %>
	<%= f.hidden_field :modo, value: "reserva" %>
	<%= f.week_field :weekdate, min: Date.today + 180 %>
	<%= f.hidden_field :user_id, value: current_user.id %>	
	<%= f.hidden_field :residence_id, value: params[:id] %>
	<%= f.submit "Reservar", :class=>'btn btn-primary' %>
	<% end %>
<% else %>
     <h6>No dispone de creditos para poder reservar</h6>
<% end %>
<% end %>
<% end %>
  <p>
	<%if Hotsale.exists?(residence_id: params[:id]) %>
	<%= link_to "FECHAS EN HOTSALE DISPONIBLES", hotsales_path , :class=>'btn btn-warning' %>
	<% end %>
</p>

<% if current_user.try(:admin?) %>

<p><h5>Crear Hotsale</h5></p>
<%= form_for Hotsale.new() do |h| %>
	<div class="form-group">
		<%= h.hidden_field :residence_id, value: params[:id] %>
	</div>
	<div class="form-group">
	<%= h.label :price, 'Precio del hot sale' %>
	<%= h.number_field :price, class: 'form-control', placeholder: 'Ingrese el valor del hotsale', required: true, min: 0 %>
	</div>
  	<div class="form-group">
		<%= h.label :weekdate, 'Semana en hot sale' %></br>
		<%= h.week_field :weekdate, min: Date.today, max: Date.today + 180, required: true %>
	</div>
  	<%= h.submit 'Guardar hot sale', class: 'btn btn-primary' %>
	<% end %>

   

<p><h5>Crear Subasta</h5></p>
    <%= form_for Auction.new() do |j| %>
   		<%= j.hidden_field :name, value: "iniciada" %>
	    <%= j.label :weekdate, 'Semana' %>
	    <%= j.week_field :weekdate, min: Date.today + 180, required: true %>
		<%= j.hidden_field :residence_id, value: params[:id] %>
		<%= j.label :monto, 'Monto Base' %>
		<%= j.number_field :monto, class: 'form-control', required: true %>
		<%= j.label :minimapuja, 'Puja Minima' %>
		<%= j.number_field :minimapuja, class: 'form-control', required: true %>
		<%= j.submit "Crear Subasta", :class=>'btn btn-primary' %>
   <% end %>
<% end %>

    <%= link_to "Volver", residences_path, class: 'btn btn-link' %>
</div>
</div>