config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 resources :users, :only => [:show]
 resources :users do
  		member do
    		get 'be_premium'
        get 'apply_premium'
        get 'enable_premium'
        get 'disable_premium'
        get 'mascreditos'
        get 'menoscreditos'
 		end
	end
 match '/users',   to: 'users#index',   via: 'get'
  resources :auctions do
      member do
        get 'finalizar'
   end
  end     

  resources :hotsales
  resources :residences
  resources :home
  resources :reservations
  #devise_for :users, controllers: {
  #      sessions: 'users/sessions'
  #    }
  get 'auctions/:id', to:'auctions#puja'
  post '/auctions/:id', to: 'auctions#puja'
  post '/residences/:id', to: 'residences#show'
  root :to => "home#index"
end

app/models/hotsale.rb
class Hotsale < ApplicationRecord


validate :validate_week

  private

  def validate_week
  	  date = DateTime.parse(weekdate)
      if date.present? && date < Date.today 
          errors.add(:weekdate, 'No puedes reservar fechas antiguas')
      end
  end

  belongs_to :residence
end

app/controllers/hotsales_controller.rb
class HotsalesController < ApplicationController

	def index
		@hotsale = Hotsale.all
		@tasks = if !params[:weekini].blank? and !params[:weekfin].blank?
          
        @NoPueden = Hotsale
        .where('weekdate BETWEEN ? AND ?', "#{params[:weekini]}", "#{params[:weekfin]}")
        #.pluck(:residence_id)
     	#@Sipueden = Residence.all.where.('id NOT IN (?)', Array.wrap(@NoPueden))
    	@Sipueden = Hotsale.where(id: @NoPueden)
     	@hotsale = @Sipueden 
     	end
    	
	end
 	
	def new
		@hotsale = Hotsale.new
	end

	def create
		@hotsale = Hotsale.new(params.require(:hotsale).permit(:weekdate, :residence_id, :price))			
			if  ( Reservation.where(residence_id: @hotsale.residence_id, weekdate: @hotsale.weekdate).exists? or Auction.where(residence_id: @hotsale.residence_id, weekdate: @hotsale.weekdate).exists? or Hotsale.where(residence_id: @hotsale.residence_id, weekdate: @hotsale.weekdate).exists? )
				redirect_to hotsales_path, notice: 'No puede crear hotsale en esa fecha, ya esta reservada o en subasta'
			else 
				if @hotsale.save
					redirect_to hotsales_path, notice: 'Se creo la hotsale'
				else redirect_to hotsales_path, notice: 'No puedes crear en fechas que ya pasaron o mayores a 6 meses' end
			end
	end

	def show
		@hotsale = Hotsale.find(params[:id])
	end


	def destroy
		@hotsale = Hotsale.find(params[:id])
		
		if current_user.present? && !current_user.admin?
			@reservation = Reservation.new(residence: @hotsale.residence, user: current_user,  weekdate: @hotsale.weekdate, modo: "hotsale")
			if @reservation.save
				redirect_to hotsales_path, notice: "Hotsale comprado exitosamente"
			else 
				redirect_to hotsales_path, notice: "Hotsale terminado, alguien ya lo compro"	end
		end
		@hotsale.destroy
		if current_user.admin?
			redirect_to hotsales_path	, notice: "Hotsale se borro"
		end

	end


	def edit
		@hotsale = Hotsale.find(params[:id])
	end


	def update
		@hotsale = Hotsale.find(params[:id])
		
			if @hotsale.update(params.require(:hotsale).permit(:weekdate, :residence_id, :price))
				redirect_to hotsales_path, notice: 'Se actualizo hotsale'
			else redirect_to hotsales_path, notice: 'No se actualizo hotsale' end
			end
		
	end

app/helpers/hotsales_helper.rb
module HotsalesHelper
end

app/views/hotsales/edit.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">




<h1>  Editar hotsale </h1>

<% if current_user.try(:admin?) %>
	<%= form_for @hotsale do |f| %>
		

<p></p>
  		<div>
  		
        <p><%= f.label :price, 'Precio' %>
        <%= f.number_field :price, class: 'form-control', required: true %></p>

  		
  		</div>
<p></p>

  		<%= f.submit "Editar hotsale", class: 'btn btn-primary' %>
      <%= link_to "Volver", hotsales_path, class: 'btn btn-primary' %>
  	</div>
<% end %>
<% end %>
  <div class="col-md-3"></div> 

</div>
</div>

app/views/hotsales/index.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">


<p></p>
<table class="table">
	<thead>
<%= form_tag(hotsales_path, method: :get) do %>
<div class="form-group">
 Disponibilidad desde semana inicial:
	<%= week_field_tag :weekini, params[:weekini] %>
</div>
<div class="form-group">
 Disponibilidad desde semana final:
  <%= week_field_tag :weekfin, params[:weekfin] %>
</div>
<%= submit_tag 'Buscar' %>
<% end %>
<table class="table">
	<thead>

		<tr>
		
			<th>Residencia</th>
			<th>Precio</th>
			<th>Semana del:</th>
		</tr>
	</thead>
	<tbody>




		<% @hotsale.each do |r| %>
			<tr>
				<% @r = Residence.find(r.residence_id) %>
        		<td><%=  @r.name  %></td>
				<td>$<%= r.price %></td>
				<% date = DateTime.parse(r.weekdate)%>
         		<td><%= date.strftime('%d/%m/%Y')   %></td>		

				<td><%=link_to 'ver', r, class: 'btn btn-success'%></td>
				<% if current_user.try(:admin?) %>
				
				<td><%=link_to 'editar', edit_hotsale_path(r), class: 'btn btn-info'%></td>
				<td><%=link_to 'eliminar', r, method: :delete,  class: 'btn btn-danger', data: { confirm: 'Realmente desea eliminar hotsale?'} %>
				<% end %>

				</td>
				<% end %>
			</tr> 
		

	</tbody>
</table>

  <div class="col-md-3"></div> 

</div>
</div>

app/views/hotsales/new.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">



<h1>  Crea una nueva hotsale </h1>
<% if current_user.try(:admin?) %>



	<%= form_for @hotsale do |f| %>
   
		  <div>
			  <%= f.label :price, 'PRECIO' %>
  		  <%= f.text_field :price, class: 'form-control' , required: true %>
        <%= f.label :weekdate, 'Semana' %>
        <%= week_field(:weekdate, min: Date.today, max: Date.today + 180, required: true)%>
        
  		</div>
  		<p></p>
  	

  		<%= f.submit "Crear hotsale", class: 'btn btn-primary' %>
      <%= link_to "Volver", hotsales_path, class: 'btn btn-primary' %>

  	</div>
<% end %>
<% end %>
  <div class="col-md-3"></div> 

</div>
</div>

app/views/hotsales/show.html.erb
  <div class="container">
  <div class="row">

  <div class="col-md-3"></div>
  <div class="col-md-6">


<table class="table">
	<thead>
		<tr>
		
			<th>Residencia ID</th>
			<th>Precio</th>
			<th>Semana</th>
		</tr>
	</thead>
	<tbody>
		<% if user_signed_in? %>
			<tr>
				<% @r = Residence.find(@hotsale.residence_id) %>
       			<td><%=  @r.name  %></td>
				<td>$<%= @hotsale.price %></td>
				<td><%= @hotsale.weekdate %></td>
			<% if !current_user.try(:admin?) %>
				<td><%=link_to 'Comprar', @hotsale, method: :delete,  class: 'btn btn-danger'%></td>
			<% end %>
	<% end %>



	</tbody>
</table>

</div> 
</div> 
  